### ISSUE TITLE
请问您在训练时有遇见过loss为nan的情况吗，这是否与学习率有关

### ISSUE THREAD

**Issue by XavierGuCN** [yuhuUSTC/FSDGN#12]

**Comment by yuhuUSTC** [comment]
没有出现过。loos为nan可能是混合精度时的数值溢出或者分母为零等情况，需要具体分析










-----原始邮件-----
发件人:XavierG ***@***.***>
发送时间:2024-09-27 16:23:24 (星期五)
收件人: yuhuUSTC/FSDGN ***@***.***>
抄送: Subscribed ***@***.***>
主题: [yuhuUSTC/FSDGN] 请问您在训练时有遇见过loss为nan的情况吗，这是否与学习率有关 (Issue #12)

**Comment by XavierGuCN** [comment]
感谢
