### ISSUE TITLE
具体的网络模型的名字叫什么

### ISSUE THREAD

**Issue by cs-hao** [yuhuUSTC/FSDGN#3]
您好，感谢你的开源，但是还有几个问题想咨询一下
1. 按照你论文的框架和代码中 /options/train/dehaze.yml 的设置，没有找到 network_g 的具体结构；
2. 你论文中提到的除了像素spatial loss，另外的Frequency loss也没有找到；
所以，你能再丰富一下你的代码么？谢谢~

**Comment by yuhuUSTC** [comment]
Previous version is released in a hurry. Revised revison is now available. Thanks for your reminder!

**Comment by it-hao** [comment]
> Previous version is released in a hurry. Revised revison is now available. Thanks for your reminder!

thank you~

**Comment by cs-hao** [comment]
> Previous version is released in a hurry. Revised revison is now available. Thanks for your reminder!

thanks~
