### ISSUE TITLE
Question about the Fig. 2. of your paper

### ISSUE THREAD

**Issue by samsara-ku** [yuhuUSTC/FSDGN#7]
![image](https://user-images.githubusercontent.com/59246456/220842051-09a246ce-b56f-45bc-aa88-6698dab630c6.png)

Hi, first thanks to your nice work.

I have a question about the Fig. 2., the t-SNE plot.

How to embed the images(i.e. hazy, clear, synhazy, synclear) into 2D space for plotting t-SNE?

Did you use any pre-trained network like ResNet?

I just want to know the way how to embed the image into vector when you plotting t-SNE, but in the paper there is no information about that.

**Comment by yuhuUSTC** [comment]
We didnot use any pretrained networks for visualization. t-SNE itself is a dimenation reduction tool, and it is well encapsulated as a package in python. You can refer to sklearn.mainfold.TSNE for more details.

**Comment by samsara-ku** [comment]
Sorry for bothering you, but how could that?

To my best knowledge, the shpae of t-SNE input should be 2 dimension like mnist image size, (28, 28).

Did you compress the images shape like (batch, channel, width, heigth) into 2D like (batch, ~~~)?

If possible, can you share any piece of codes for t-SNE plotting?

**Comment by yuhuUSTC** [comment]
You can send an email to yuhu520@mail.ustc.edu.cn. I will share you the t-SNE code.

**Comment by samsara-ku** [comment]
Thank you! :)
